
import javax.swing.JOptionPane;
import dao.ConnectionProvider;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class AddMedicine extends javax.swing.JFrame {
    private ConnectionProvider con;
    /**
     * Creates new form AddMedichine
     */
    public AddMedicine() {
        initComponents();
        setLocationRelativeTo(null);
        con = new ConnectionProvider();
        String username = Session.getInstance().getUsername();
        //String userIdSession = Session.getInstance().getUserID(); 
        loadCompany();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_nameMedicine = new javax.swing.JTextField();
        Txt_Quantity = new javax.swing.JTextField();
        Txt_priceUnit = new javax.swing.JTextField();
        Txt_expDate = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        Btn_Close = new javax.swing.JButton();
        Cmb_Company = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("Add Medicine");

        jLabel4.setText("Name of Medicine");

        jLabel5.setText("Name of Company");

        jLabel6.setText("Price Per Unit");

        jlabel.setText("Quantity");

        jLabel8.setText("Expired Date");

        Txt_nameMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_nameMedicineActionPerformed(evt);
            }
        });

        Txt_Quantity.setText(" ");
        Txt_Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_QuantityActionPerformed(evt);
            }
        });

        Txt_priceUnit.setText(" ");
        Txt_priceUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_priceUnitActionPerformed(evt);
            }
        });

        Txt_expDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_expDateKeyReleased(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        Btn_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        Btn_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CloseActionPerformed(evt);
            }
        });

        Cmb_Company.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose Company--" }));
        Cmb_Company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_CompanyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(302, 302, 302)
                .addComponent(Btn_Close)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cmb_Company, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(Txt_nameMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(Txt_Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Txt_priceUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addComponent(saveBtn)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(Txt_expDate, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(115, 115, 115))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Close)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_priceUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_nameMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_expDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cmb_Company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_priceUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_priceUnitActionPerformed
        String priceStr = Txt_priceUnit.getText().replace(",", ""); 
        double pricePerUnit = Double.parseDouble(priceStr);

    }//GEN-LAST:event_Txt_priceUnitActionPerformed

    
    private String generateMedicineID() {
    String newID = "M001"; 
    try {
        Connection conn = con.getCon();
        String sql = "SELECT id_medicine FROM medicines ORDER BY id_medicine DESC LIMIT 1";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String lastID = rs.getString("id_medicine"); 
            String olahID = lastID.substring(lastID.length() - 3);
            int process = Integer.parseInt(olahID) + 1;
            newID = "M" + String.format("%03d", process);
        }
        
        rs.close();
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error generating medicine ID: " + e.getMessage());
    }
    return newID;
}


    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String NameofCompany = (String) Cmb_Company.getSelectedItem();
        String NameofMedicine = Txt_nameMedicine.getText();
        String Quantity = Txt_Quantity.getText();
        String PricePerUnit = Txt_priceUnit.getText();
        String ExpiredDate = Txt_expDate.getText();
        
        String IDSupplier = companyMap.get(NameofCompany);
        String IDMedicine = generateMedicineID();


        if(NameofCompany.equals("")){
            JOptionPane.showMessageDialog(null, "Name of company field is required!");
        } else if(NameofMedicine.equals("")){
            JOptionPane.showMessageDialog(null, "Name of medicine field is required!");
        } else if(Quantity.equals("")){
            JOptionPane.showMessageDialog(null, "Quantity field is required!");
        } else if(PricePerUnit.equals("")){
            JOptionPane.showMessageDialog(null, "Price per unit is required!");
        } else if(ExpiredDate.equals("")){
            JOptionPane.showMessageDialog(null, "Expired date of medicine is required!");
        } else{
            try {
                Connection conn = con.getCon();
                
                String checkMedicineSql = "SELECT id_medicine FROM medicines WHERE name_medicine = ?";
                PreparedStatement checkPst = conn.prepareStatement(checkMedicineSql);
                checkPst.setString(1, NameofMedicine);
                ResultSet rsCheck = checkPst.executeQuery();

                if (rsCheck.next()) {
                JOptionPane.showMessageDialog(null, "Medicine already exists!");
                return; 
            }

            rsCheck.close();
            checkPst.close();
            
                String sql = "INSERT INTO medicines (id_medicine, id_supplier, name_medicine, stock_quantity, price, expired_date) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, IDMedicine);
                pst.setString(2, IDSupplier);
                pst.setString(3, NameofMedicine);
                pst.setString(4, Quantity);
                pst.setString(5, PricePerUnit);
                pst.setString(6, ExpiredDate);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Medicine Added Succesfully");
                setVisible(true);
                pst.close();
                conn.close();
                
                this.dispose();
                new AddMedicine().setVisible(true);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
    }//GEN-LAST:event_saveBtnActionPerformed
 }
    
            
    private void Txt_nameMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_nameMedicineActionPerformed

    }//GEN-LAST:event_Txt_nameMedicineActionPerformed

    private void Btn_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_Btn_CloseActionPerformed
    
    private void Cmb_CompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_CompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_CompanyActionPerformed

    private void Txt_expDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_expDateKeyReleased
        String dateText = Txt_expDate.getText(); 
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        try {
            sdf.setLenient(false); 
            sdf.parse(dateText);   
            Txt_expDate.setForeground(java.awt.Color.BLACK); 
        } catch (ParseException e) {
            Txt_expDate.setForeground(java.awt.Color.RED); 
        }
    }//GEN-LAST:event_Txt_expDateKeyReleased

    private void Txt_QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_QuantityActionPerformed
   
    private HashMap<String, String> companyMap = new HashMap<>();

    private void loadCompany() {
        try {
            Connection conn = con.getCon();
            String sql = "SELECT id_supplier, name_supplier FROM suppliers";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String id = rs.getString("id_supplier");
            String name = rs.getString("name_supplier");
            companyMap.put(name, id);
            Cmb_Company.addItem(name); 
        }
        rs.close();
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error loading type transactions: " + e);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Close;
    private javax.swing.JComboBox<String> Cmb_Company;
    private javax.swing.JTextField Txt_Quantity;
    private javax.swing.JTextField Txt_expDate;
    private javax.swing.JTextField Txt_nameMedicine;
    private javax.swing.JTextField Txt_priceUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
