/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import dao.ConnectionProvider;
import java.sql.*;
import java.util.HashMap;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
/**
 *
 * @author user
 */
public class SellMedicine extends javax.swing.JFrame {
    private ConnectionProvider con;
 
    /**
     * Creates new form SellMedicine
     */
    public SellMedicine() {
        initComponents();
        setLocationRelativeTo(null);
        con = new ConnectionProvider(); 
        loadMedicineNames();
        loadTypeTransaction();
        loadCompany();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Txt_TransactionDate = new javax.swing.JTextField();
        Cmb_Transaction = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Cmb_Medicine = new javax.swing.JComboBox<>();
        Txt_PricePerUnit = new javax.swing.JTextField();
        Txt_AmountPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txt_Qty = new javax.swing.JTextField();
        Btn_save = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Btn_close = new javax.swing.JButton();
        Cmb_CompanyName = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Txt_PaymentMethod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("Sell Medicine");

        jLabel2.setText("Transaction Date");

        jLabel3.setText("Company Name");

        jLabel4.setText("Type Transaction");

        Txt_TransactionDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TransactionDateActionPerformed(evt);
            }
        });
        Txt_TransactionDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_TransactionDateKeyReleased(evt);
            }
        });

        Cmb_Transaction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose Transaction--" }));
        Cmb_Transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_TransactionActionPerformed(evt);
            }
        });

        jLabel6.setText("Name of Medicine");

        jLabel7.setText("Price Per Unit");

        jLabel8.setText("Amount Price");

        Cmb_Medicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose Medicine--" }));
        Cmb_Medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_MedicineActionPerformed(evt);
            }
        });

        Txt_AmountPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_AmountPriceActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantity");

        Txt_Qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_QtyKeyReleased(evt);
            }
        });

        Btn_save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        Btn_save.setText("Save");
        Btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_saveActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("* * * Thank You * * *");

        Btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        Btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_closeActionPerformed(evt);
            }
        });

        Cmb_CompanyName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose Company--" }));
        Cmb_CompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_CompanyNameActionPerformed(evt);
            }
        });

        jLabel10.setText("Payment Method");

        Txt_PaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_PaymentMethodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(Btn_close)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Txt_TransactionDate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cmb_Transaction, javax.swing.GroupLayout.Alignment.LEADING, 0, 230, Short.MAX_VALUE)
                    .addComponent(Cmb_CompanyName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cmb_Medicine, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Btn_save)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_PricePerUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_PaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_AmountPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Txt_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Btn_close))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_TransactionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Cmb_Transaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(Txt_PricePerUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(Cmb_Medicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(Txt_AmountPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cmb_CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(Txt_PaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(Btn_save)
                .addGap(71, 71, 71)
                .addComponent(jLabel9)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void Txt_AmountPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_AmountPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_AmountPriceActionPerformed

    private String generateTransactionID() {
    String newID = "T001"; 
    try {
        Connection conn = con.getCon();
        String sql = "SELECT id_transaction FROM transactions ORDER BY id_transaction DESC LIMIT 1";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String lastID = rs.getString("id_transaction"); 
            String olahID = lastID.substring(lastID.length() - 3);
            int process = Integer.parseInt(olahID) + 1;
            newID = "T" + String.format("%03d", process);
        }
        
        rs.close();
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error generating transaction ID: " + e.getMessage());
    }
    return newID;
}
    private String generateTDetailsID() {
    String newID = "D001"; 
    try {
        Connection conn = con.getCon();
        String sql = "SELECT id_transaction_details FROM transaction_details ORDER BY id_transaction_details DESC LIMIT 1";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String lastID = rs.getString("id_transaction_details"); 
            String olahID = lastID.substring(lastID.length() - 3);
            int process = Integer.parseInt(olahID) + 1;
            newID = "D" + String.format("%03d", process);
        }
        
        rs.close();
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error generating transaction detail ID: " + e.getMessage());
    }
    return newID;
}

    private void Btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_saveActionPerformed
        String userIdSession = Session.getInstance().getUserID();
        if (userIdSession != null && !userIdSession.isEmpty()) {
        saveTransaction(userIdSession);
        } else {
        JOptionPane.showMessageDialog(null, "Error: User session is invalid!");
        }
    }//GEN-LAST:event_Btn_saveActionPerformed

    private void saveTransaction(String UserID) { 
        System.out.println("Session Debug - Username: " + Session.getInstance().getUsername());
        System.out.println("Session Debug - UserID: " + Session.getInstance().getUserID());
    
        String username = Session.getInstance().getUsername();
        String userIdSession = Session.getInstance().getUserID(); 
        
        if (userIdSession == null || userIdSession.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Error: User session is invalid!xxx");
        return;
        }

        String NameofCompany = (String) Cmb_CompanyName.getSelectedItem();
        String NameofMedicine = (String) Cmb_Medicine.getSelectedItem();
        String TypeTransaction = (String) Cmb_Transaction.getSelectedItem();
        String TransactionDate = Txt_TransactionDate.getText();
        String Quantity = Txt_Qty.getText();
        String PricePerUnit = Txt_PricePerUnit.getText();
        String AmountPrice = Txt_AmountPrice.getText();
        String PaymentMethod = Txt_PaymentMethod.getText();
        
        String IDSupplier = companyMap.get(NameofCompany);
        String IDMedicine = medicineMap.get(NameofMedicine);
        String IDTransaction = generateTransactionID();
        //String IDTransactionDetail = generateTransactionDetailsID();
        
    try {
        Connection conn = con.getCon();
        conn.setAutoCommit(false);
        
        String getMedicineIdSQL = "SELECT id_medicine FROM medicines WHERE name_medicine = ?";
        PreparedStatement pst1 = conn.prepareStatement(getMedicineIdSQL);
        pst1.setString(1, NameofMedicine);
        ResultSet rs1 = pst1.executeQuery();
        
        String medicineId = null;
        if (rs1.next()) {
            medicineId = rs1.getString("id_medicine");
        }
        rs1.close();
        pst1.close();

       
        String getCompanyIdSQL = "SELECT id_supplier FROM suppliers WHERE name_supplier = ?";
        PreparedStatement pst2 = conn.prepareStatement(getCompanyIdSQL);
        pst2.setString(1, NameofCompany);
        ResultSet rs2 = pst2.executeQuery();
        
        String companyId = null;
        if (rs2.next()) {
            companyId = rs2.getString("id_supplier");
        }
        rs2.close();
        pst2.close();

        int quantity = Integer.parseInt(Quantity);
        String transactionType = (String) Cmb_Transaction.getSelectedItem();

        String getStockQuantitySQL = "SELECT stock_quantity FROM medicines WHERE id_medicine = ?";
        PreparedStatement pst3 = conn.prepareStatement(getStockQuantitySQL);
        pst3.setString(1, medicineId);
        ResultSet rs3 = pst3.executeQuery();

        int currentStock = 0;
        if (rs3.next()) {
            currentStock = rs3.getInt("stock_quantity");
        }
        rs3.close();
        pst3.close();

        int newStock; 
        if (transactionType.equals("IN")){
            newStock = currentStock + quantity;
        } else {
            newStock = currentStock - quantity;
        }
        
        if (newStock < 0) {
            JOptionPane.showMessageDialog(null, "insufficient stock!");
            return;
        }


        String insertSQL = "INSERT INTO transactions (id_transaction, id_user, transaction_date, type_transaction, payment_total, payment_method) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement pst4 = conn.prepareStatement(insertSQL);
        pst4.setString(1, IDTransaction);
        pst4.setString(2, userIdSession);
        pst4.setString(3, TransactionDate);
        pst4.setString(4, TypeTransaction);
        pst4.setString(5, AmountPrice);
        pst4.setString(6, PaymentMethod);
        pst4.executeUpdate();
        pst4.close();
        
        int finalAmount = quantity * Integer.parseInt(PricePerUnit);
        
        String insertTransactionDetailsSQL = "INSERT INTO transaction_details (id_transaction_details, id_transaction, id_medicine, total_medicine, final_amount) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pst5 = conn.prepareStatement(insertTransactionDetailsSQL);
        String IDTransactionDetail = generateTDetailsID();
        pst5.setString(1, IDTransactionDetail);
        pst5.setString(2, IDTransaction);
        pst5.setString(3, medicineId);
        pst5.setInt(4, quantity);
        pst5.setInt(5, finalAmount);
        pst5.executeUpdate();
        pst5.close();

        String updateStockSQL = "UPDATE medicines SET stock_quantity = ? WHERE id_medicine = ?";
        PreparedStatement pst6 = conn.prepareStatement(updateStockSQL);
        pst6.setInt(1, newStock);
        pst6.setString(2, medicineId);
        pst6.executeUpdate();
        pst6.close();
        
        conn.commit();
        conn.close();
        JOptionPane.showMessageDialog(null, "Transaction saved successfully!");
        setVisible(true);
                
        this.dispose();
        new SellMedicine().setVisible(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}
    
  
    private void Btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_closeActionPerformed
        setVisible(false);
    }//GEN-LAST:event_Btn_closeActionPerformed

    private void Cmb_MedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_MedicineActionPerformed
        String selectedMedicine = (String) Cmb_Medicine.getSelectedItem();
        if (selectedMedicine != null&& !selectedMedicine.trim().isEmpty()){
            try {
                Connection conn = con.getCon();
                String sql = "SELECT price FROM medicines WHERE name_medicine = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, selectedMedicine.trim());
                ResultSet rs = pst.executeQuery();
        
                
                if(rs.next()){
                    String price = rs.getString("price");
                    Txt_PricePerUnit.setText(price);
                } else {
                    Txt_PricePerUnit.setText("");
                }
                rs.close();
                pst.close();
                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
            }
        }
    }//GEN-LAST:event_Cmb_MedicineActionPerformed
    
    private HashMap<String, String> medicineMap = new HashMap<>();

    private void loadMedicineNames() {
        try {
            Connection conn = con.getCon();
            String sql = "SELECT id_medicine, name_medicine FROM medicines";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String id = rs.getString("id_medicine");
            String name = rs.getString("name_medicine");
            medicineMap.put(name, id);
            Cmb_Medicine.addItem(name); 
        }
        rs.close();
        pst.close();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error loading medicines: " + e);
    }
  }
    
    private void Txt_QtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_QtyKeyReleased
    try {
        BigDecimal price = new BigDecimal(Txt_PricePerUnit.getText().replace(",", "")); 
        BigDecimal quantity = new BigDecimal(Txt_Qty.getText()); 
        BigDecimal total = price.multiply(quantity);
        //JOptionPane.showMessageDialog(null, price + " x "+ quantity);
        Txt_AmountPrice.setText(String.valueOf(total));
        } catch (NumberFormatException e) {
        Txt_AmountPrice.setText(""); 
    }
    }//GEN-LAST:event_Txt_QtyKeyReleased

    private void Cmb_TransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_TransactionActionPerformed
        
    }//GEN-LAST:event_Cmb_TransactionActionPerformed
     private HashMap<String, String> typeTransactionMap = new HashMap<>();

    private void loadTypeTransaction() {
        try {
            Connection conn = con.getCon();
            String sql = "SELECT id_type_transaction, type_transaction FROM type_transactions";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String id = rs.getString("id_type_transaction");
            String name = rs.getString("type_transaction");
            typeTransactionMap.put(name, id);
            Cmb_Transaction.addItem(name); 
        }
        rs.close();
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error loading type transactions: " + e);
    }
}
    private void Txt_TransactionDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TransactionDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TransactionDateActionPerformed

    private void Txt_TransactionDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_TransactionDateKeyReleased

        String dateText = Txt_TransactionDate.getText(); 
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        try {
            sdf.setLenient(false); 
            sdf.parse(dateText);   
            Txt_TransactionDate.setForeground(java.awt.Color.BLACK); 
        } catch (ParseException e) {
            Txt_TransactionDate.setForeground(java.awt.Color.RED); 
        }
    }//GEN-LAST:event_Txt_TransactionDateKeyReleased

    private void Cmb_CompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_CompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_CompanyNameActionPerformed

    private void Txt_PaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_PaymentMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_PaymentMethodActionPerformed
    private HashMap<String, String> companyMap = new HashMap<>();

    private void loadCompany() {
        try {
            Connection conn = con.getCon();
            String sql = "SELECT id_supplier, name_supplier FROM suppliers";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String id = rs.getString("id_supplier");
            String name = rs.getString("name_supplier");
            companyMap.put(name, id);
            Cmb_CompanyName.addItem(name); 
        }
        rs.close();
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error loading type transactions: " + e);
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_close;
    private javax.swing.JButton Btn_save;
    private javax.swing.JComboBox<String> Cmb_CompanyName;
    private javax.swing.JComboBox<String> Cmb_Medicine;
    private javax.swing.JComboBox<String> Cmb_Transaction;
    private javax.swing.JTextField Txt_AmountPrice;
    private javax.swing.JTextField Txt_PaymentMethod;
    private javax.swing.JTextField Txt_PricePerUnit;
    private javax.swing.JTextField Txt_Qty;
    private javax.swing.JTextField Txt_TransactionDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
